{% set version = "0.0.0" %}
package:
  name: rag_utils
  version: {{ version }}


source:
  path: ..


build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - python {{PY_VER}}*
    - cmake
    - pybind11
    - xtensor-python
    - xtensor
    - boost >=1.63
  run:
    - python {{PY_VER}}*
    - numpy # do not need to constrain np version


test:
  imports:
    - rag_utils
